### ISSUE TITLE
Автоматическое определение трейдера

### ISSUE THREAD

**Issue by Mastic0re** [johnpantini/ppp#11]
Концепция: иметь единое окно терминала, через которое можно торговать всеми настроенными брокерами/трейдерами. Скорее всего это уже есть в долгосрочных планах, я опишу свое видение.
1. Сделать поле "Трейдер" в виджетах необязательным, либо добавить дополнительную опцию "Автоподбор трейдера".
2. При поиске тикера в выпадающем списке такого виджета выводить строчку на каждое совпадение по комбинации "Брокер+трейдер".
3. При выборе строки проставлять трейдера в настройку всех виджетов в той же группе.
4. Иметь возможность настроить трейдера по умолчанию для биржи. При получении тикера из внешних сигналов (кнопки ТГ) использовать трейдера по умолчанию.

**Comment by johnpantini** [comment]
Эти пожелания не будут реализованы в обозримом будущем
