### ISSUE TITLE
Предложения

### ISSUE THREAD

**Issue by Noxqee** [johnpantini/ppp#19]
Виджет ленты сделок.
В зависимости от времени торгов, хотелось бы иметь возможность настраивать объем "видимых сделок" моментально, посредством дополнительной функции или шаблона.

К примеру, по США
4:00 - 9:30 - 1 лот
9:30 - 16:00 - 100 лотов
16:00 -20:00 - 1 лот.

Баг при сохранении виджета:
Когда сохраняешь виджет (тот же T&S) лента сделок меняет свой тикер на предыдущий. Терпимо, но неприятно.

Виджет торговой паузы:
Хотелось бы иметь звуковое оповещение при публикации, некритично, т.к. есть телеграм-бот, но "реакция" PPP сильно быстрее чем TG. Это же касается и новостей.

Ни одно из предложений не является критически необходимым для работы, но, как мне кажется, могло бы помочь торговцу при работе.

**Comment by johnpantini** [comment]
Баг при сохранении виджета ленты сделок либо не понял, либо не могу воспроизвести. Можно видео или gif с воспроизведением?

**Comment by Noxqee** [comment]
https://github.com/johnpantini/ppp/assets/106952648/694344fb-23ee-4dbe-8fda-c1fb853e9f71

**Comment by Noxqee** [comment]
Спасибо, Джон Фазерович!
