### ISSUE TITLE
Частичное исполнение заявки

### ISSUE THREAD

**Issue by alexandrdragin** [johnpantini/ppp#8]
_На 99% уверен что это не баг, а еще в работе, 
но на всякий зарепочу все равно_ 

При частичном исполнении заявки в стакане не обновляется счетчик и перестают работать скальперские кнопки 

![telegram-cloud-photo-size-2-5427168083530860005-y](https://user-images.githubusercontent.com/13015093/218420472-bdbe0b32-021e-44b6-94fc-a7e533b633e7.jpg)

**Comment by johnpantini** [comment]
Это же трейдер Тинькофф, верно?

**Comment by alexandrdragin** [comment]
Да, если проблема не их стороне, и нет обратной связи по частичному исполнению заявки то ладно.
